---
title: "Projects"
---

To view all of my projects, please visit my [github page](https://github.com/khangluu4903){.uri}!

**Amazon Sales Data Statistical Modeling Competition**

-   Developed and optimized ML regression models to predict total sales from a dataset with 34 variables and 5894 rows.

-   Utilized tidymodels and tidyverse for preprocessing, including scaling 13 predictors, which reduced RMSE by 0.09%, and hyperparameter tuning 7 random forest and linear regression models on training data with 2942 observations.

-   Achieved 95.82% accuracy on test data with the top-performing random forest model, placing 3th out of 16 teams.

**California Housing Price Prediction**

-   Utilized pandas, numpy, matplotlib, and seaborn for data manipulation, visualization, and exploration.

-   Conducted data exploration and transformation, including log transformations of skewed variables to achieve a normal distribution.

-   Employed scikit-learn for splitting the data into training and testing sets, as well as for fitting the linear multiple regression model.

-   Utilized statsmodels for additional statistical analysis, including checking coefficients, p-values, and model summary statistics.

-   Achieved R-squared value of 0.686, indicating the model explains about 68.6% of the variation in housing prices.

**Telco Customer Churn**

-   Explored the dataset's shape and information to understand its structure. Checked for missing values and converted columns to the correct data types. Used pandas to handle data.

-   Calculated the overall churn rate and visualized it using a bar chart. Analyzed churn rates based on customer tenure, finding a significant decrease in churn as tenure increases. Used matplotlib for visualization.

-   Built a linear regression model to predict churn rate based on tenure. The model showed a strong correlation (R-squared value of 0.83) between tenure and churn rate. Used scipy.stats for the linear regression analysis.

-   Analyzed churn rates for different Telco services like Phone Service, Online Security, and Streaming TV. Identified services with higher churn rates, providing insights for targeted improvements.

-   Investigated churn rates for customers using multiple Telco services. Found that customers with 2 services had the highest churn rate, suggesting a need for bundled service offerings or enhanced retention strategies.

-   Provided actionable recommendations for Telco, such as focusing on new customers for retention efforts, improving services with high churn rates, and promoting bundled service offerings based on the analysis.
